### ISSUE TITLE
Невозможно установить модуль

### ISSUE THREAD

**Issue by cybergeo82** [nextgis/qgis_dumploadfield#4]
Не удалось загрузить модуль 'dumploadfield' из-за ошибки при вызове метода classFactory() 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:\NextGIS\lib\python38\site-packages\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python/plugins\dumploadfield\__init__.py", line 30, in classFactory
    from .dumpfield import dumpfield
  File "C:\NextGIS\lib\python38\site-packages\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python/plugins\dumploadfield\dumpfield.py", line 34, in 
    import resources_rc
  File "C:\NextGIS\lib\python38\site-packages\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Версия Python: 3.8.10 (default, Oct 14 2022, 19:11:57) [MSC v.1929 64 bit (AMD64)] 
Версия: 3.24.0-Tisler Tisler, c32947d8 

Расположение Python:
C:\Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python/plugins\ngq_rosreestr_tools\packages
C:/NextGIS/share/ngqgis/python
C:/Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python
C:/Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python/plugins
C:/NextGIS/share/ngqgis/python/plugins
C:\NextGIS\lib\python38
C:\NextGIS\lib\python38\site-packages
C:\NextGIS\lib\python38\lib-dynload
C:\NextGIS
C:\NextGIS\bin\python38.zip
C:\NextGIS\bin
C:/Users/Cybergeo/AppData/Roaming/NextGIS/ngqgis\profiles\default/python

**Comment by simgislab** [comment]
fixed in version 0.3.1
